# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4170ee9a1e49bc7ad5d5eae24e516bf477decc98b42e069ea42ed17fba6810becf19a2010c93336b5ccb4c23bb661b7f5235e5fe8477c3d109525c11f8d78e3b

test:
  secret_key_base: b4cb582e74845bf407c1bcd0749b81ae8cb337c529e567c6eafc01a7453febb565293190a5c7f8e87316581829bb1dd7dbe90dc43120bfd689da287c26dc7662

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
